version: '3'

services:
  nextapp:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
      - ./backend:/app/backend
    ports:
      - "3000:3000"
      - "8000:8000"
    environment:
      - NODE_ENV=development
    command: ./start.sh